definitions:
  models.User:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/get_user:
    get:
      consumes:
      - application/json
      description: Get User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: User
      tags:
      - user
swagger: "2.0"
